#include "components.h"

ECS_COMPONENT_DECLARE(Position);
ECS_COMPONENT_DECLARE(Renderable);
ECS_COMPONENT_DECLARE(Viewshed);
ECS_COMPONENT_DECLARE(Name);
ECS_COMPONENT_DECLARE(CombatStats);
ECS_COMPONENT_DECLARE(MeleeAttacker);
ECS_COMPONENT_DECLARE(Potion);
ECS_COMPONENT_DECLARE(InBackpack);
ECS_COMPONENT_DECLARE(ItemPickup);
ECS_COMPONENT_DECLARE(DrinkPotion);
ECS_COMPONENT_DECLARE(DropItem);

ECS_TAG_DECLARE(Player);
ECS_TAG_DECLARE(Monster);
ECS_TAG_DECLARE(BlocksTile);
ECS_TAG_DECLARE(Item);
