#include "components.h"

ECS_COMPONENT_DECLARE(Position);
ECS_COMPONENT_DECLARE(Renderable);
ECS_COMPONENT_DECLARE(Viewshed);
ECS_COMPONENT_DECLARE(Name);

ECS_TAG_DECLARE(Player);
ECS_TAG_DECLARE(Monster);
